### ISSUE TITLE
Non-existent static dir causes failure

### ISSUE THREAD

**Issue by javabrett** [kennethreitz/flask-common#7]
In https://github.com/kennethreitz/flask-common/blob/master/flask_common.py#L112 a behaviour change in Python and Whitenoise can cause an error if the passed `root=url_for('static', filename='')` directory `static/` does not exist.

/cc https://github.com/kennethreitz/httpbin/issues/403
/cc https://github.com/evansd/whitenoise/issues/166

**Comment by CMCDragonkai** [comment]
Is this still an issue?

**Comment by javabrett** [comment]
https://github.com/evansd/whitenoise/issues/166 is fixed in https://github.com/evansd/whitenoise/commit/2a883f5cda0336dbefebef7bb918c3a2b167a70d and WhiteNoise v4.0, so I expect updating WhiteNoise would fix this for all.
